config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  mount ActionCable.server => '/cable'

  resources :persons do
    resources :localizations
    resources :themes
    resources :fanfics do
      resources :chapters
    end
  end

  resources :read_fanfics do
    resources :read_chapters
  end

  resources :comments

  resources :tags do
    collection do
      get :get_all
      get :hide_all
    end
  end

  resources :searches

  resources :ratings

  root to: "read_fanfics#index"
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController

  before_action :check_user

  def index
    @users = User.all.to_a
  end
  
  def show
    if current_user.admin_role
      @fanfics = Fanfic.where(user_id: params[:id]).to_a
    else
      @fanfics = Fanfic.where(user_id: current_user.id).to_a
    end
  end

  def update
    set_admin(params)
    ban_unban(params)
    redirect_to controller: "persons", action: "index"
  end

  def destroy
    User.destroy(params[:id])
    redirect_to controller: "persons", action: "index"
  end

  protected

  def check_user
    if params[:id] != current_user.id && !current_user.admin_role
      redirect_to root_path
    end
  end

  private

  def set_admin(params)
    if params[:admin_role] || params[:user_role]
      User.update(params[:id], admin_role: params[:admin_role], user_role: params[:user_role])
    end
  end

  def ban_unban(params)
    if params[:ban_unban]
      if User.find(params[:id]).banned
        User.update(params[:id], banned: 0)
      else
        User.update(params[:id], banned: 1)
      end
    end
  end
end

app/helpers/persons_helper.rb
module PersonsHelper

end

app/views/persons/index.html.erb
<%= javascript_include_tag "persons_index" %>
<table class="table table-hover">
  <thead>
  <tr>
    <th scope="col">id</th>
    <th scope="col">Email</th>
    <th scope="col">Login</th>
    <th scope="col">Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <% if user.banned %>
      <tr style="cursor: pointer; background-color: #ff9085" id="user">
        <td data-href= "<%= person_path(user.id) %>"><%= user.id %></td>
        <td data-href= "<%= person_path(user.id) %>"><%= user.email %></td>
        <td data-href= "<%= person_path(user.id) %>"><%= user.login %></td>
        <td>
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Action
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <%= link_to 'Set admin', person_path(user.id, admin_role: 1, user_role: 0), { class: 'dropdown-item', method: :patch } %>
            <%= link_to 'Ban/Unban', person_path(user.id, ban_unban: 1), { class: 'dropdown-item', method: :patch } %>
            <%= link_to 'Delete', person_path(user.id), { class: 'dropdown-item', method: :delete } %>
          </div>
        </td>
      </tr>
    <% else %>
      <tr style="cursor: pointer;" id="user">
        <td data-href= "<%= person_path(user.id) %>"><%= user.id %></td>
        <td data-href= "<%= person_path(user.id) %>"><%= user.email %></td>
        <td data-href= "<%= person_path(user.id) %>"><%= user.login %></td>
        <td>
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Action
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <%= link_to 'Set admin', person_path(user.id, admin_role: 1, user_role: 0), { class: 'dropdown-item', method: :patch } %>
            <%= link_to 'Ban/Unban', person_path(user.id, ban_unban: 1), { class: 'dropdown-item', method: :patch } %>
            <%= link_to 'Delete', person_path(user.id), { class: 'dropdown-item', method: :delete } %>
          </div>
        </td>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

app/views/persons/show.html.erb
<%= javascript_include_tag "persons_show" %>
<script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>

<div class="user-setting">
  <div class="dropdown local-button">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <%= t('user.theme') %>
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <%= link_to t('user.light'), edit_person_theme_path(params[:id], theme: 'light'), {class: "dropdown-item"} %>
      <%= link_to t('user.dark'), edit_person_theme_path(params[:id], theme: 'dark'), {class: "dropdown-item"} %>
    </div>
  </div>
  <div class="dropdown local-button">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <%= t('user.localization') %>
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <%= link_to t('user.russian'), edit_person_localization_path(params[:id], localization: 'ru'), {class: "dropdown-item"} %>
      <%= link_to t('user.english'), edit_person_localization_path(params[:id], localization: 'en'), {class: "dropdown-item"} %>
    </div>
  </div>
</div>

<div class="table-block">
  <table class="table table-hover table-bordered">
    <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col"><%= t('table.fanfics.image') %></th>
      <th scope="col"><%= t('table.fanfics.title') %></th>
      <th scope="col"><%= t('table.fanfics.genre') %></th>
      <th scope="col"><%= t('table.fanfics.description') %></th>
      <th scope="col"><%= t('table.fanfics.actions') %></th>
    </tr>
    </thead>
    <tbody>
    <% @fanfics.each_with_index do |fanfic, index| %>
      <tr style="cursor: pointer;">
        <td data-href= "<%= person_fanfic_chapters_path(params[:id], fanfic.id) %>" scope="row"><%= index.to_i + 1 %></td>
        <td data-href= "<%= person_fanfic_chapters_path(params[:id], fanfic.id) %>" class="table-image"><img src="<%= fanfic.image %>" alt="" style="width: 100%" ></td>
        <td data-href= "<%= person_fanfic_chapters_path(params[:id], fanfic.id) %>"><%= fanfic.title %></td>
        <td data-href= "<%= person_fanfic_chapters_path(params[:id], fanfic.id) %>"><%= fanfic.genre %></td>
        <td data-href= "<%= person_fanfic_chapters_path(params[:id], fanfic.id) %>"><%= fanfic.description %></td>
        <td>
          <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Actions
            </button>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
              <%= link_to 'Edit', edit_person_fanfic_path(params[:id], fanfic.id), { class: 'dropdown-item' } %>
              <%= link_to 'Delete', person_fanfic_path(params[:id], fanfic.id), { method: "delete", class: 'dropdown-item' } %>
              <% if current_user.admin_role %>
                <%= link_to "Create new chapter", new_person_fanfic_chapter_path(params[:id], fanfic.id), { class: "new-chapter dropdown-item" } %>
              <% else %>
                <%= link_to "Create new chapter", new_person_fanfic_chapter_path(current_user.id, fanfic.id), { class: "new-chapter dropdown-item" } %>
              <% end %>
            </div>
          </div>
        </td>
      </tr>
    <% end %>
    </tbody>
    <tfoot>
      <tr>
        <% if current_user.admin_role %>
          <td colspan="6" style="text-align: center; font-size: 2em; color: #7f7f7f" data-href= "<%= new_person_fanfic_path(params[:id]) %>">
            <i class="fas fa-plus"></i>
          </td>
        <% else %>
          <td colspan="6" style="text-align: center; font-size: 2em; color: #7f7f7f" data-href= "<%= new_person_fanfic_path(current_user.id) %>">
            <i class="fas fa-plus"></i>
          </td>
        <% end %>
      </tr>
    </tfoot>
  </table>
</div>