config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  mount ActionCable.server => '/cable'

  resources :persons do
    resources :localizations
    resources :themes
    resources :fanfics do
      resources :chapters
    end
  end

  resources :read_fanfics do
    resources :read_chapters
  end

  resources :comments

  resources :tags do
    collection do
      get :get_all
      get :hide_all
    end
  end

  resources :searches

  resources :ratings

  root to: "read_fanfics#index"
end

app/controllers/read_fanfics_controller.rb
class ReadFanficsController < ApplicationController
  def index
    case params[:search]
      when 'search_any'
        search_by_tags_any(params[:tags])
      when 'search_all'
        search_by_tags_all(params[:tags])
      when 'search'
        search_by_criteria(params[:criteria])
      else
        @fanfics = Fanfic.order(created_at: :desc).page(params[:page]).includes(:ratings, :comments)
        get_ratings(@fanfics)
    end
    @tags = Tag.order(count: :desc).limit(10)
  end

  def show
    @chapters = Chapter.where(fanfic_id: params[:id])
  end

  private

  def search_by_tags_all(tags)
    unless tags.nil?
      @fanfics = Fanfic.all
      tags.each do |tag|
        @fanfics = @fanfics.where("tags LIKE :tag", tag: "%#{tag}%").order(created_at: :desc).page(params[:page])
      end
      get_ratings(@fanfics)
    else
      @fanfics = Fanfic.order(created_at: :desc).page(params[:page])
      get_ratings(@fanfics)
    end
  end

  def search_by_tags_any(tags)
    @fanfics = []
    unless tags.nil?
      @fanfics = Fanfic.where(generate_query(tags)).order(created_at: :desc).page(params[:page])
      get_ratings(@fanfics)
    else
      @fanfics = Fanfic.order(created_at: :desc).page(params[:page])
      get_ratings(@fanfics)
    end
  end

  def search_by_criteria(criteria)
    unless criteria.nil?
      @fanfics = Fanfic.order(created_at: :desc).includes(:comments, :chapters).where("fanfics.title LIKE :criteria or description LIKE :criteria or genre LIKE :criteria or comment LIKE :criteria or chapters.title LIKE :criteria or text LIKE :criteria", criteria: "%#{criteria}%").references(:comments, :chapters).page(params[:page])
      get_ratings(@fanfics)
    else
      @fanfics = Fanfic.order(created_at: :desc).page(params[:page])
      get_ratings(@fanfics)
    end
  end

  def generate_query(tags)
    query = "tags LIKE '%#{tags[0]}%'"
    tags.drop(1).each_index do |index|
      query += " OR tags LIKE '%#{tags[index + 1]}%'"
    end
    query
  end

  def get_ratings(fanfics)
    @ratings = fanfics.map { |elem| elem.ratings.pluck(:rating) }.map { |arr| if arr.empty?
                                                                                0
                                                                              else
                                                                                arr.sum / arr.size
                                                                              end }
    get_comments(fanfics)
  end

  def get_comments(fanfics)
    @comments = fanfics.map { |elem| elem.comments.to_a.size }
  end
end

app/helpers/read_fanfics_helper.rb
module ReadFanficsHelper
end

app/views/read_fanfics/_fanfics.html.erb
<% fanfics.each_with_index do |fanfic, index| %>
    <div class="fanfic-display">
      <%= link_to read_fanfic_path(fanfic.id), {class: "row"} do %>
        <%= render partial: 'read_fanfics/rating', locals: { fanfic: fanfic, average: ratings[index] } %>
        <div class="col-md-4">
          <img src="<%= fanfic.image %>" alt="" >
        </div>
        <div class="col-md-8">
          <h2><%= fanfic.title %></h2>
          <p>
            <%= fanfic.description %>
          </p>
        </div>
        <div class="col-md-12">
          <% fanfic.tags.split(' ').each do |tag| %>
            <span class="badge badge-info"><%= tag %></span>
          <% end %>
        </div>
        <hr>
        <div class="col-md-12 fanfic-comments">
          <p><i class="fas fa-comments"></i> <%= comments[index] %></p>
        </div>
      <% end %>
    </div>
<% end %>
<div class="container pagination justify-content-center" >
  <%= paginate fanfics %>
</div>

app/views/read_fanfics/_rating.html.erb
<div class="col-md-12">
  <% 5.times do |index| %>
    <% if index + 1 > average %>
      <i class="fas fa-star"></i>
    <% else %>
      <i class="fas fa-star" style="color: black"></i>
    <% end %>
  <% end %>
</div>

app/views/read_fanfics/_tags.html.erb
<% tags.each do |tag| %>
  <span class="badge badge-secondary"><%= tag.tag %></span>
<% end %>
<br>
<% if is_hidden %>
  <p id="show-tags" class="show-tags"><%= t('tags_button.show_all') %></p>
<% else %>
  <p id="hide-tags" class="show-tags"><%= t('tags_button.hide_tags') %></p>
<% end %>
<div class="btn-group" role="group" aria-label="Basic example">
  <button type="button" class="btn btn-secondary" id="tags-search-any"><%= t('tags_button.any') %></button>
  <button type="button" class="btn btn-secondary" id="tags-search-all"><%= t('tags_button.all') %></button>
</div>

app/views/read_fanfics/index.html.erb
<script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
<%= javascript_include_tag "read_fanfics_index" %>
<% if flash[:error] %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= flash[:error] %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<div class="tag-cloud">
  <%= render partial: 'read_fanfics/tags', locals: { tags: @tags, is_hidden: true } %>
</div>
<div id="fanfics">
  <%= render partial: 'read_fanfics/fanfics', locals: { fanfics: @fanfics, ratings: @ratings, comments: @comments } %>
</div>

app/views/read_fanfics/show.html.erb
<%= javascript_include_tag "read_fanfics_show" %>
<% if @chapters.any? %>
  <% @chapters.each do |chapter| %>
    <div data-href= "<%= read_fanfic_read_chapter_path(params[:id], chapter.id) %>" class="chapters jumbotron row">
      <img src="<%= chapter.image %>" alt="">
      <div class="col">
        <h2><%= chapter.title %></h2>
        <hr>
        <div> <%= markdown(chapter.text) %></div>
      </div>
    </div>
  <% end %>
<% else %>
  <p class="empty-fanfic">
    <%= t('fanfics.empty') %>¯\_(ツ)_/¯
  </p>
<% end %>