config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  mount ActionCable.server => '/cable'

  resources :persons do
    resources :localizations
    resources :themes
    resources :fanfics do
      resources :chapters
    end
  end

  resources :read_fanfics do
    resources :read_chapters
  end

  resources :comments

  resources :tags do
    collection do
      get :get_all
      get :hide_all
    end
  end

  resources :searches

  resources :ratings

  root to: "read_fanfics#index"
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  has_many :fanfics
  has_many :comments, through: :fanfics
  has_many :users, through: :comments
  has_many :ratings
  belongs_to :fanfic
end

app/controllers/chapters_controller.rb
class ChaptersController < FanficsController

  before_action :check_user

  def new
    @chapter = Chapter.new
  end

  def index
    @chapters = Chapter.where(fanfic_id: params[:fanfic_id]).to_a
  end

  def create
    new_chapter_params = params[:chapter]
    new_chapter_params.merge!({ user_id: params[:person_id].to_s, fanfic_id: params[:fanfic_id] })
    Chapter.create(
        title: new_chapter_params[:title], text: new_chapter_params[:text],
        image: new_chapter_params[:image],
        fanfic_id: new_chapter_params[:fanfic_id]).save
    redirect_to person_path(current_user.id)
  end

  def edit
    @chapter = Chapter.find(params[:id])
  end

  def update
    Chapter.update( params[:id],
        title: params[:chapter][:title], text: params[:chapter][:text],
        image: params[:chapter][:image]).save
    redirect_to person_path(current_user.id)
  end

  protected

  def check_user
    if Fanfic.find(params[:fanfic_id]).user_id != current_user.id && !current_user.admin_role
      redirect_to root_path
    end
  end
end

app/views/chapters/edit.html.erb
<%= javascript_include_tag "jquery.ui.widget", "jquery.iframe-transport",
                           "jquery.fileupload", "jquery.cloudinary" %>

<%= cloudinary_js_config %>
<%= javascript_include_tag "chapters_new" %>

<%= form_for @chapter, url: {action: "update"} do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control"%>
  </div>

  <div id="dropzone-area" class="dropzone">

  </div>

  <div class="form-group">
    <%= f.label :text %>
    <%= f.text_area :text, class: "form-control"%>
  </div>

  <div class="form-group" style="display: none">
    <%= f.text_field :image, class: "form-control image"%>
  </div>

  <%= f.submit "Save", class: "btn btn-primary" %>
<% end %>

app/views/chapters/index.html.erb
<%= javascript_include_tag "chapters_index" %>
<% @chapters.each do |chapter| %>
  <%= link_to 'Edit', edit_person_fanfic_chapter_path(params[:person_id], params[:fanfic_id], chapter.id), { class: "col-md-12 edit-link" } %>
  <div data-href= "<%= read_fanfic_read_chapter_path(params[:fanfic_id], chapter.id) %>" class="chapters jumbotron row">
    <img src="<%= chapter.image %>" alt="">
    <div class="col">
      <h2><%= chapter.title %></h2>
      <hr>
      <div> <%= markdown(chapter.text) %></div>
    </div>
  </div>
<% end %>

app/views/chapters/new.html.erb
<%= javascript_include_tag "jquery.ui.widget", "jquery.iframe-transport",
                           "jquery.fileupload", "jquery.cloudinary" %>
<%= cloudinary_js_config %>
<%= javascript_include_tag "chapters_new" %>
<h1 class="fanfic-header">Write your magnum opus</h1>

<%= form_for @chapter, url: {action: "create"} do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control"%>
  </div>

  <div id="dropzone-area" class="dropzone">

  </div>

  <div class="form-group">
    <%= f.label :text %>
    <%= f.text_area :text, class: "form-control"%>
  </div>

  <div class="form-group" style="display: none">
    <%= f.text_field :image, class: "form-control image"%>
  </div>

  <%= f.submit "Save", class: "btn btn-primary" %>
<% end %>

app/views/chapters/show.html.erb
<%= javascript_include_tag "chapters_show" %>
<%= link_to "Create new chapter", new_person_fanfic_chapter_path(current_user.id, fanfic.id) %>
<% @chapters.each do |chapter| %>
  <div data-href= "<%= read_fanfic_read_chapter_path(params[:id], chapter.id) %>">
    <img src="<%= chapter.image %>" alt="">
    <h2><%= chapter.title %></h2>
  </div>
<% end %>