config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  mount ActionCable.server => '/cable'

  resources :persons do
    resources :localizations
    resources :themes
    resources :fanfics do
      resources :chapters
    end
  end

  resources :read_fanfics do
    resources :read_chapters
  end

  resources :comments

  resources :tags do
    collection do
      get :get_all
      get :hide_all
    end
  end

  resources :searches

  resources :ratings

  root to: "read_fanfics#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.admin_role?
      can :manage_users, :all
    else
      can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  has_many :fanfics
  has_many :comments, through: :fanfics
  has_many :users, through: :comments
  has_many :ratings
  belongs_to :fanfic
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :fanfic
  belongs_to :user
  belongs_to :like
end

app/models/fanfic.rb
class Fanfic < ApplicationRecord
  has_many :comments
  has_many :users, through: :comments
  has_many :ratings, through: :chapters
  has_many :chapters, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  has_many :user
  has_many :comment
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :chapter
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments
  has_many :fanfics

  validates :login, uniqueness: true

  devise :database_authenticatable, :registerable, :confirmable, :async,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/chapters_controller.rb
class ChaptersController < FanficsController

  before_action :check_user

  def new
    @chapter = Chapter.new
  end

  def index
    @chapters = Chapter.where(fanfic_id: params[:fanfic_id]).to_a
  end

  def create
    new_chapter_params = params[:chapter]
    new_chapter_params.merge!({ user_id: params[:person_id].to_s, fanfic_id: params[:fanfic_id] })
    Chapter.create(
        title: new_chapter_params[:title], text: new_chapter_params[:text],
        image: new_chapter_params[:image],
        fanfic_id: new_chapter_params[:fanfic_id]).save
    redirect_to person_path(current_user.id)
  end

  def edit
    @chapter = Chapter.find(params[:id])
  end

  def update
    Chapter.update( params[:id],
        title: params[:chapter][:title], text: params[:chapter][:text],
        image: params[:chapter][:image]).save
    redirect_to person_path(current_user.id)
  end

  protected

  def check_user
    if Fanfic.find(params[:fanfic_id]).user_id != current_user.id && !current_user.admin_role
      redirect_to root_path
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ActionController::Base
  def create
    comment = Comment.new comment: params[:comment][:comment],
                          fanfic_id: params[:comment][:fanfic_id],
                          user_id: current_user.id
    comment.save
    update_comments(comment)
  end

  def update
    if !Like.where(user_id: current_user.id, comment_id: params[:id]).any?
      if current_user
        comment = Comment.find(params[:id])
        comment.likes += 1
        comment.save
        Like.create comment_id: params[:id], user_id: current_user.id
        update_comments(comment)
      end
    end
  end

  private

  def update_comments(comment)
    ActionCable.server.broadcast 'comments',
                                 message: comment.comment,
                                 likes: comment.likes,
                                 user: comment.user.login,
                                 id: comment.id
    head :ok
  end
end

app/controllers/fanfics_controller.rb
class FanficsController < PersonsController

  before_action :check_user

  def new
    @genres = Genre.pluck(:name, :name)
    @fanfic = Fanfic.new
  end

  def create
    new_fanfic_params = params[:fanfic]
    new_fanfic_params.merge!(user_id: params[:person_id].to_s)
    add_tags(params[:fanfic][:tags])
    add_fanfic(new_fanfic_params)
    redirect_to person_path(current_user.id)
  end

  def edit
    @genres = Genre.pluck(:name, :name)
    @fanfic = Fanfic.find(params[:id])
  end

  def update
    Fanfic.update( params[:id],
                   title: params[:fanfic][:title], description: params[:fanfic][:description],
                   image: params[:fanfic][:image])
    redirect_to person_path(current_user.id)
  end

  def destroy
    Fanfics.find(params[:id]).destroy
    redirect_to person_path(current_user.id)
  end

  protected

  def check_user
    if params[:person_id] != current_user.id && !current_user.admin_role
      redirect_to root_path
    end
  end

  private

  def add_tags(tags)
    tags_array = tags.split
    tags_array.each {|tag|
      active_record_tag = Tag.where(tag: tag).first
      if active_record_tag
        active_record_tag.update(count: active_record_tag[:count] + 1)
      else
        Tag.create(tag: tag)
      end }
  end

  def add_fanfic(new_fanfic_params)
    add_tags(params[:fanfic][:tags])
    Fanfic.create(
        title: new_fanfic_params[:title], description: new_fanfic_params[:description],
        image: new_fanfic_params[:image],
        genre: new_fanfic_params[:genre],
        user_id: new_fanfic_params[:user_id],
        tags: new_fanfic_params[:tags]).save
  end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController

  before_action :check_user

  def index
    @users = User.all.to_a
  end
  
  def show
    if current_user.admin_role
      @fanfics = Fanfic.where(user_id: params[:id]).to_a
    else
      @fanfics = Fanfic.where(user_id: current_user.id).to_a
    end
  end

  def update
    set_admin(params)
    ban_unban(params)
    redirect_to controller: "persons", action: "index"
  end

  def destroy
    User.destroy(params[:id])
    redirect_to controller: "persons", action: "index"
  end

  protected

  def check_user
    if params[:id] != current_user.id && !current_user.admin_role
      redirect_to root_path
    end
  end

  private

  def set_admin(params)
    if params[:admin_role] || params[:user_role]
      User.update(params[:id], admin_role: params[:admin_role], user_role: params[:user_role])
    end
  end

  def ban_unban(params)
    if params[:ban_unban]
      if User.find(params[:id]).banned
        User.update(params[:id], banned: 0)
      else
        User.update(params[:id], banned: 1)
      end
    end
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def create
    existing_rating = Rating.where(user_id: current_user.id, chapter_id: params[:chapter])
    if existing_rating.any?
      existing_rating.update(rating: params[:rating].to_i)
    else
      Rating.create(user_id: current_user.id,
                    chapter_id: params[:chapter],
                    rating: params[:rating].to_i)
    end
    show_average_rating(Rating.where(chapter_id: params[:chapter]))
    render partial: 'read_chapters/rating', locals: { rating: @rating,
                                                      user_rating: params[:rating],
                                                      chapter: params[:chapter]}
  end

  private

  def show_average_rating(ratings)
    if ratings.any?
      @rating = ratings.average(:rating)
    else
      @rating = "No one rate this post yet"
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    render json: { tags: Tag.pluck(:tag, :tag) }
  end

  def get_all
    render partial: "read_fanfics/tags", locals: { tags: Tag.order(count: :desc), is_hidden: false }
  end

  def hide_all
    render partial: "read_fanfics/tags", locals: { tags: Tag.order(count: :desc).limit(10), is_hidden: true }
  end
end

app/controllers/themes_controller.rb
class ThemesController < PersonsController
  def edit
    User.update(params[:id], theme: params[:theme]).save
    redirect_to person_path(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
    options = {
        autolink: true,
        no_intra_emphasis: true,
        fenced_code_blocks: true,
        lax_html_blocks: true,
        strikethrough: true,
        superscript: true,
        space_after_headers: true
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  end
end

app/helpers/persons_helper.rb
module PersonsHelper

end

app/helpers/read_fanfics_helper.rb
module ReadFanficsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Funfix</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag @theme, media: 'all', 'data-turbolinks-track' => true%>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag :defaults %>
  <% content_for :javascript_includes do %>
    <%= javascript_include_tag "search.js" %>
  <% end %>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-light">
    <%= link_to 'Fanfics', root_path, { class: "navbar-brand"} %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <div class="input-group search">
            <%= form_tag(read_fanfics_path, method: "get") do %>
              <%= text_field_tag(:criteria, nil, {class: "form-control search-input"}) %>
              <%= hidden_field_tag "search", "search" %>
              <span class="input-group-btn">
                <%= submit_tag(t('search.field'), {class: "btn btn-secondary search-button"}) %>
              </span>
            <% end %>
          </div>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item" style="margin: auto">
            <div class="dropdown">
              <button class="btn btn-secondary dropdown-toggle current-user" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= t('profile.greetings') %>, <%= current_user.login %>
              </button>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="btnGroupDrop1">
                <%= link_to(t('link_text.my_profile'), person_path(current_user.id), :method => :get, :class => "dropdown-item" )%>
                <% if can? :manage_users, User %>
                  <%= link_to(t('link_text.show_users'), persons_path, { class: "dropdown-item" })%>
                <% end %>
                <%= link_to(t('link_text.logout'), destroy_user_session_path, :method => :delete, :class => "dropdown-item")%>
              </div>
            </div>
          </li>
        <% else %>
          <li class="nav-item" style="margin: auto 5% auto 0;">
            <%= link_to t('link_text.register'), new_user_registration_path, :class => "nav-link" %>
            <%= link_to t('link_text.login'), new_user_session_path, :class => "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>

  <%= yield %>

</body>
</html>

app/views/layouts/markitup.html.erb
<!DOCTYPE html>
<html>
<head>
<title>markItUp! preview template</title>
<style type="text/css">
/* preview style examples */
body {
  background-color: #efefef;
  font: 70% Verdana, Arial, Helvetica, sans-serif;
}
</style>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/searches/index.html.erb
<div id="fanfics">
  <%= render partial: 'read_fanfics/fanfics', locals: { fanfics: @fanfics } %>
</div>
<script>
    $(document).on("click", "tbody > tr", function() {
        window.location = "http://localhost:3000" + $(this).data("href");
    });
</script>